"""Add occasion and special_requests to reservations

Revision ID: 92726c89675c
Revises: c98ca70c83af
Create Date: 2025-08-28 09:56:48.215475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92726c89675c'
down_revision = 'c98ca70c83af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('occassion', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('special_requests', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'special_requests')
    op.drop_column('reservations', 'occassion')
    # ### end Alembic commands ###
